keys:
  - &key age1ch2vy79p2dwxn4myapyvdzgrasm2al5us98y4duh2tfqusaaxptqleqptv
  - &mbp-asahi-ssh age1ajymdz0vs6nkk6ycmpp6dry9nsc586x0lcdhm4ws0h97fw764s2q7j4a69
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *key
      - *mbp-asahi-ssh
