# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/48b12621-3987-48af-ad25-aa6eb25ca379";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/8b0529d2-0485-4c71-b2aa-04084aaaadee";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/540c84e0-8cc2-493f-b317-044ef4ed53e8";
    fsType = "ext4";
  };

  swapDevices = [{ device = "/swapfile"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
